name: Generate Readme Stats

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Prepare dist Folder
        run: |
          mkdir -p dist
          chmod -R u+rw dist

      - name: Generate Snake Art
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/grid-snake-light.svg
            dist/grid-snake-dark.svg?palette=github-dark

      - name: Generate Stats Dark
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true&theme=dracula
          path: dist/stats-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Stats Light
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=${{ github.repository_owner }}&show_icons=true
          path: dist/stats-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Dark
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=dracula&langs_count=8&layout=compact
          path: dist/top-langs-dark.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Light
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&langs_count=8&layout=compact
          path: dist/top-langs-light.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Changes
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
